# 📊 PUNKT 3: INDIKATOR-DEFINITIONEN
# Alle 551+ Indikatoren aus 8 Bibliotheken

def get_all_indicators():
    """Definiert alle 551 verfügbaren Indikatoren aus 8 Bibliotheken"""
    return {
        "vbt": {
            "ADX": {"params": ["window"], "defaults": [14], "category": "Momentum"},
            "ATR": {"params": ["window"], "defaults": [14], "category": "Volatility"},
            "BBANDS": {"params": ["window", "alpha"], "defaults": [20, 2], "category": "Trend"},
            "BOLB": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "FIXLB": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "FMAX": {"params": ["window"], "defaults": [14], "category": "Math"},
            "FMEAN": {"params": ["window"], "defaults": [14], "category": "Math"},
            "FMIN": {"params": ["window"], "defaults": [14], "category": "Math"},
            "FSTD": {"params": ["window"], "defaults": [14], "category": "Math"},
            "HURST": {"params": ["window"], "defaults": [100], "category": "Statistical"},
            "MA": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "MACD": {"params": ["fast_window", "slow_window", "signal_window"], "defaults": [12, 26, 9], "category": "Momentum"},
            "MEANLB": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "MSD": {"params": ["window"], "defaults": [20], "category": "Statistical"},
            "OBV": {"params": [], "defaults": [], "category": "Volume"},
            "OHLCSTCX": {"params": ["window"], "defaults": [14], "category": "Price"},
            "OHLCSTX": {"params": ["window"], "defaults": [14], "category": "Price"},
            "OLS": {"params": ["window"], "defaults": [20], "category": "Statistical"},
            "PATSIM": {"params": ["window"], "defaults": [20], "category": "Pattern"},
            "PIVOTINFO": {"params": ["window"], "defaults": [20], "category": "Support/Resistance"},
            "PIVOTLB": {"params": ["window"], "defaults": [20], "category": "Support/Resistance"},
            "RAND": {"params": [], "defaults": [], "category": "Math"},
            "RANDNX": {"params": ["window"], "defaults": [20], "category": "Math"},
            "RANDX": {"params": ["window"], "defaults": [20], "category": "Math"},
            "RPROB": {"params": ["window"], "defaults": [20], "category": "Statistical"},
            "RPROBCX": {"params": ["window"], "defaults": [20], "category": "Statistical"},
            "RPROBNX": {"params": ["window"], "defaults": [20], "category": "Statistical"},
            "RPROBX": {"params": ["window"], "defaults": [20], "category": "Statistical"},
            "RSI": {"params": ["window"], "defaults": [14], "category": "Momentum"},
            "SIGDET": {"params": ["window"], "defaults": [20], "category": "Signal"},
            "STCX": {"params": ["window"], "defaults": [14], "category": "Momentum"},
            "STOCH": {"params": ["k_window", "d_window"], "defaults": [5, 3], "category": "Momentum"},
            "STX": {"params": ["window"], "defaults": [14], "category": "Momentum"},

            "TRENDLB": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "VWAP": {"params": [], "defaults": [], "category": "Price"}
        },
        "talib": {
            # Math Transform Functions
            "ACOS": {"params": [], "defaults": [], "category": "Math"},
            "ASIN": {"params": [], "defaults": [], "category": "Math"},
            "ATAN": {"params": [], "defaults": [], "category": "Math"},
            "CEIL": {"params": [], "defaults": [], "category": "Math"},
            "COS": {"params": [], "defaults": [], "category": "Math"},
            "COSH": {"params": [], "defaults": [], "category": "Math"},
            "EXP": {"params": [], "defaults": [], "category": "Math"},
            "FLOOR": {"params": [], "defaults": [], "category": "Math"},
            "LN": {"params": [], "defaults": [], "category": "Math"},
            "LOG10": {"params": [], "defaults": [], "category": "Math"},
            "SIN": {"params": [], "defaults": [], "category": "Math"},
            "SINH": {"params": [], "defaults": [], "category": "Math"},
            "SQRT": {"params": [], "defaults": [], "category": "Math"},
            "TAN": {"params": [], "defaults": [], "category": "Math"},
            "TANH": {"params": [], "defaults": [], "category": "Math"},
            "ADD": {"params": [], "defaults": [], "category": "Math"},
            "DIV": {"params": [], "defaults": [], "category": "Math"},
            "MAX": {"params": ["timeperiod"], "defaults": [30], "category": "Math"},
            "MAXINDEX": {"params": ["timeperiod"], "defaults": [30], "category": "Math"},
            "MIN": {"params": ["timeperiod"], "defaults": [30], "category": "Math"},
            "MININDEX": {"params": ["timeperiod"], "defaults": [30], "category": "Math"},
            "MINMAX": {"params": ["timeperiod"], "defaults": [30], "category": "Math"},
            "MINMAXINDEX": {"params": ["timeperiod"], "defaults": [30], "category": "Math"},
            "MULT": {"params": [], "defaults": [], "category": "Math"},
            "SUB": {"params": [], "defaults": [], "category": "Math"},
            "SUM": {"params": ["timeperiod"], "defaults": [30], "category": "Math"},

            # Overlap Studies
            "SMA": {"params": ["timeperiod"], "defaults": [20], "category": "Trend"},
            "EMA": {"params": ["timeperiod"], "defaults": [20], "category": "Trend"},
            "WMA": {"params": ["timeperiod"], "defaults": [20], "category": "Trend"},
            "DEMA": {"params": ["timeperiod"], "defaults": [20], "category": "Trend"},
            "TEMA": {"params": ["timeperiod"], "defaults": [20], "category": "Trend"},
            "TRIMA": {"params": ["timeperiod"], "defaults": [20], "category": "Trend"},
            "KAMA": {"params": ["timeperiod"], "defaults": [20], "category": "Trend"},
            "MAMA": {"params": ["fastlimit", "slowlimit"], "defaults": [0.5, 0.05], "category": "Trend"},
            "MAVP": {"params": ["minperiod", "maxperiod", "matype"], "defaults": [2, 30, 0], "category": "Trend"},
            "T3": {"params": ["timeperiod", "vfactor"], "defaults": [5, 0.7], "category": "Trend"},
            "BBANDS": {"params": ["timeperiod", "nbdevup", "nbdevdn", "matype"], "defaults": [20, 2, 2, 0], "category": "Volatility"},
            "MIDPOINT": {"params": ["timeperiod"], "defaults": [14], "category": "Trend"},
            "MIDPRICE": {"params": ["timeperiod"], "defaults": [14], "category": "Trend"},
            "SAR": {"params": ["acceleration", "maximum"], "defaults": [0.02, 0.2], "category": "Trend"},
            "SAREXT": {"params": ["startvalue", "offsetonreverse", "accelerationinitlong", "accelerationlong", "accelerationmaxlong", "accelerationinitshort", "accelerationshort", "accelerationmaxshort"], "defaults": [0, 0, 0.02, 0.02, 0.2, 0.02, 0.02, 0.2], "category": "Trend"},

            # Momentum Indicators
            "RSI": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "MACD": {"params": ["fastperiod", "slowperiod", "signalperiod"], "defaults": [12, 26, 9], "category": "Momentum"},
            "MACDEXT": {"params": ["fastperiod", "fastmatype", "slowperiod", "slowmatype", "signalperiod", "signalmatype"], "defaults": [12, 0, 26, 0, 9, 0], "category": "Momentum"},
            "MACDFIX": {"params": ["signalperiod"], "defaults": [9], "category": "Momentum"},
            "STOCH": {"params": ["fastkperiod", "slowkperiod", "slowkmatype", "slowdperiod", "slowdmatype"], "defaults": [5, 3, 0, 3, 0], "category": "Momentum"},
            "STOCHF": {"params": ["fastkperiod", "fastdperiod", "fastdmatype"], "defaults": [5, 3, 0], "category": "Momentum"},
            "STOCHRSI": {"params": ["timeperiod", "fastkperiod", "fastdperiod", "fastdmatype"], "defaults": [14, 5, 3, 0], "category": "Momentum"},
            "WILLR": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "ADX": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "ADXR": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "APO": {"params": ["fastperiod", "slowperiod", "matype"], "defaults": [12, 26, 0], "category": "Momentum"},
            "AROON": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "AROONOSC": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "BOP": {"params": [], "defaults": [], "category": "Momentum"},
            "CCI": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "CMO": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "DX": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "MINUS_DI": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "MINUS_DM": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "MOM": {"params": ["timeperiod"], "defaults": [10], "category": "Momentum"},
            "PLUS_DI": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "PLUS_DM": {"params": ["timeperiod"], "defaults": [14], "category": "Momentum"},
            "PPO": {"params": ["fastperiod", "slowperiod", "matype"], "defaults": [12, 26, 0], "category": "Momentum"},
            "ROC": {"params": ["timeperiod"], "defaults": [10], "category": "Momentum"},
            "ROCP": {"params": ["timeperiod"], "defaults": [10], "category": "Momentum"},
            "ROCR": {"params": ["timeperiod"], "defaults": [10], "category": "Momentum"},
            "ROCR100": {"params": ["timeperiod"], "defaults": [10], "category": "Momentum"},
            "TRIX": {"params": ["timeperiod"], "defaults": [30], "category": "Momentum"},
            "ULTOSC": {"params": ["timeperiod1", "timeperiod2", "timeperiod3"], "defaults": [7, 14, 28], "category": "Momentum"},

            # Volume Indicators
            "AD": {"params": [], "defaults": [], "category": "Volume"},
            "ADOSC": {"params": ["fastperiod", "slowperiod"], "defaults": [3, 10], "category": "Volume"},
            "OBV": {"params": [], "defaults": [], "category": "Volume"},
            "MFI": {"params": ["timeperiod"], "defaults": [14], "category": "Volume"},

            # Volatility Indicators
            "ATR": {"params": ["timeperiod"], "defaults": [14], "category": "Volatility"},
            "NATR": {"params": ["timeperiod"], "defaults": [14], "category": "Volatility"},
            "TRANGE": {"params": [], "defaults": [], "category": "Volatility"},

            # Price Transform
            "AVGPRICE": {"params": [], "defaults": [], "category": "Price"},
            "MEDPRICE": {"params": [], "defaults": [], "category": "Price"},
            "TYPPRICE": {"params": [], "defaults": [], "category": "Price"},
            "WCLPRICE": {"params": [], "defaults": [], "category": "Price"},

            # Cycle Indicators
            "HT_DCPERIOD": {"params": [], "defaults": [], "category": "Cycle"},
            "HT_DCPHASE": {"params": [], "defaults": [], "category": "Cycle"},
            "HT_PHASOR": {"params": [], "defaults": [], "category": "Cycle"},
            "HT_SINE": {"params": [], "defaults": [], "category": "Cycle"},
            "HT_TRENDMODE": {"params": [], "defaults": [], "category": "Cycle"},
            "HT_TRENDLINE": {"params": [], "defaults": [], "category": "Cycle"},

            # Statistic Functions
            "BETA": {"params": ["timeperiod"], "defaults": [5], "category": "Statistical"},
            "CORREL": {"params": ["timeperiod"], "defaults": [30], "category": "Statistical"},
            "LINEARREG": {"params": ["timeperiod"], "defaults": [14], "category": "Statistical"},
            "LINEARREG_ANGLE": {"params": ["timeperiod"], "defaults": [14], "category": "Statistical"},
            "LINEARREG_INTERCEPT": {"params": ["timeperiod"], "defaults": [14], "category": "Statistical"},
            "LINEARREG_SLOPE": {"params": ["timeperiod"], "defaults": [14], "category": "Statistical"},
            "STDDEV": {"params": ["timeperiod", "nbdev"], "defaults": [5, 1], "category": "Statistical"},
            "TSF": {"params": ["timeperiod"], "defaults": [14], "category": "Statistical"},
            "VAR": {"params": ["timeperiod", "nbdev"], "defaults": [5, 1], "category": "Statistical"},

            # Pattern Recognition (alle 61 Candlestick Patterns)
            "CDL2CROWS": {"params": [], "defaults": [], "category": "Pattern"},
            "CDL3BLACKCROWS": {"params": [], "defaults": [], "category": "Pattern"},
            "CDL3INSIDE": {"params": [], "defaults": [], "category": "Pattern"},
            "CDL3LINESTRIKE": {"params": [], "defaults": [], "category": "Pattern"},
            "CDL3OUTSIDE": {"params": [], "defaults": [], "category": "Pattern"},
            "CDL3STARSINSOUTH": {"params": [], "defaults": [], "category": "Pattern"},
            "CDL3WHITESOLDIERS": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLABANDONEDBABY": {"params": ["penetration"], "defaults": [0.3], "category": "Pattern"},
            "CDLADVANCEBLOCK": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLBELTHOLD": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLBREAKAWAY": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLCLOSINGMARUBOZU": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLCONCEALBABYSWALL": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLCOUNTERATTACK": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLDARKCLOUDCOVER": {"params": ["penetration"], "defaults": [0.5], "category": "Pattern"},
            "CDLDOJI": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLDOJISTAR": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLDRAGONFLYDOJI": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLENGULFING": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLEVENINGDOJISTAR": {"params": ["penetration"], "defaults": [0.3], "category": "Pattern"},
            "CDLEVENINGSTAR": {"params": ["penetration"], "defaults": [0.3], "category": "Pattern"},
            "CDLGAPSIDESIDEWHITE": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLGRAVESTONEDOJI": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLHAMMER": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLHANGINGMAN": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLHARAMI": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLHARAMICROSS": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLHIGHWAVE": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLHIKKAKE": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLHIKKAKEMOD": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLHOMINGPIGEON": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLIDENTICAL3CROWS": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLINNECK": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLINVERTEDHAMMER": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLKICKING": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLKICKINGBYLENGTH": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLLADDERBOTTOM": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLLONGLEGGEDDOJI": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLLONGLINE": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLMARUBOZU": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLMATCHINGLOW": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLMATHOLD": {"params": ["penetration"], "defaults": [0.5], "category": "Pattern"},
            "CDLMORNINGDOJISTAR": {"params": ["penetration"], "defaults": [0.3], "category": "Pattern"},
            "CDLMORNINGSTAR": {"params": ["penetration"], "defaults": [0.3], "category": "Pattern"},
            "CDLONNECK": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLPIERCING": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLRICKSHAWMAN": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLRISEFALL3METHODS": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLSEPARATINGLINES": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLSHOOTINGSTAR": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLSHORTLINE": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLSPINNINGTOP": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLSTALLEDPATTERN": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLSTICKSANDWICH": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLTAKURI": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLTASUKIGAP": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLTHRUSTING": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLTRISTAR": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLUNIQUE3RIVER": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLUPSIDEGAP2CROWS": {"params": [], "defaults": [], "category": "Pattern"},
            "CDLXSIDEGAP3METHODS": {"params": [], "defaults": [], "category": "Pattern"}
        },
        "pandas_ta": {
            # Overlap Studies (Moving Averages)
            "SMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "EMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "WMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "HMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "DEMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "TEMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "TRIMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "KAMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "ALMA": {"params": ["length", "sigma", "offset"], "defaults": [20, 6, 0.85], "category": "Trend"},
            "FWMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "JMA": {"params": ["length", "phase"], "defaults": [20, 0], "category": "Trend"},
            "PWMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "RMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "SINWMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "SWMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "T3": {"params": ["length", "a"], "defaults": [20, 0.7], "category": "Trend"},
            "VWMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "ZLMA": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "VIDYA": {"params": ["length"], "defaults": [14], "category": "Trend"},

            # Momentum Indicators
            "RSI": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "MACD": {"params": ["fast", "slow", "signal"], "defaults": [12, 26, 9], "category": "Momentum"},
            "STOCH": {"params": ["k", "d", "smooth_k"], "defaults": [14, 3, 3], "category": "Momentum"},
            "STOCHRSI": {"params": ["length", "rsi_length", "k", "d"], "defaults": [14, 14, 3, 3], "category": "Momentum"},
            "WILLR": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "ADX": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "AROON": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "CCI": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "CMO": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "ROC": {"params": ["length"], "defaults": [10], "category": "Momentum"},
            "RSX": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "TRIX": {"params": ["length"], "defaults": [30], "category": "Momentum"},
            "TSI": {"params": ["fast", "slow"], "defaults": [25, 13], "category": "Momentum"},
            "UO": {"params": ["fast", "medium", "slow"], "defaults": [7, 14, 28], "category": "Momentum"},
            "APO": {"params": ["fast", "slow"], "defaults": [12, 26], "category": "Momentum"},
            "BOP": {"params": [], "defaults": [], "category": "Momentum"},
            "BRAR": {"params": ["length"], "defaults": [26], "category": "Momentum"},
            "CFO": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "CG": {"params": ["length"], "defaults": [10], "category": "Momentum"},
            "CTI": {"params": ["length"], "defaults": [12], "category": "Momentum"},
            "ER": {"params": ["length"], "defaults": [10], "category": "Momentum"},
            "ERI": {"params": ["length"], "defaults": [13], "category": "Momentum"},
            "FISHER": {"params": ["length"], "defaults": [9], "category": "Momentum"},
            "INERTIA": {"params": ["length", "rvi_length"], "defaults": [20, 14], "category": "Momentum"},
            "KDJ": {"params": ["length"], "defaults": [9], "category": "Momentum"},
            "KST": {"params": ["roc1", "roc2", "roc3", "roc4", "sma1", "sma2", "sma3", "sma4"], "defaults": [10, 15, 20, 30, 10, 10, 10, 15], "category": "Momentum"},
            "MOM": {"params": ["length"], "defaults": [10], "category": "Momentum"},
            "PPO": {"params": ["fast", "slow"], "defaults": [12, 26], "category": "Momentum"},
            "PGO": {"params": ["length"], "defaults": [14], "category": "Momentum"},
            "PSL": {"params": ["open_length", "close_length"], "defaults": [12, 26], "category": "Momentum"},
            "PVO": {"params": ["fast", "slow"], "defaults": [12, 26], "category": "Momentum"},
            "QQE": {"params": ["length", "smooth"], "defaults": [14, 5], "category": "Momentum"},
            "RVGI": {"params": ["length", "swma_length"], "defaults": [14, 4], "category": "Momentum"},
            "RVI": {"params": ["length"], "defaults": [10], "category": "Momentum"},
            "SMI": {"params": ["fast", "slow", "signal"], "defaults": [5, 20, 5], "category": "Momentum"},
            "SQUEEZE": {"params": ["bb_length", "bb_std", "kc_length", "kc_scalar"], "defaults": [20, 2, 20, 1.5], "category": "Momentum"},
            "SQUEEZE_PRO": {"params": ["bb_length", "bb_std", "kc_length", "kc_scalar_wide", "kc_scalar_normal", "kc_scalar_narrow"], "defaults": [20, 2, 20, 2, 1.5, 1], "category": "Momentum"},
            "STC": {"params": ["tclength", "fast", "slow"], "defaults": [10, 23, 50], "category": "Momentum"},
            "TD_SEQ": {"params": [], "defaults": [], "category": "Momentum"},
            "TSI": {"params": ["fast", "slow"], "defaults": [25, 13], "category": "Momentum"},
            "TTM_TREND": {"params": ["length"], "defaults": [6], "category": "Momentum"},
            "UI": {"params": ["length"], "defaults": [14], "category": "Momentum"},

            # Volatility Indicators
            "BBANDS": {"params": ["length", "std"], "defaults": [20, 2], "category": "Volatility"},
            "ATR": {"params": ["length"], "defaults": [14], "category": "Volatility"},
            "NATR": {"params": ["length"], "defaults": [14], "category": "Volatility"},
            "TRUE_RANGE": {"params": [], "defaults": [], "category": "Volatility"},
            "ACCBANDS": {"params": ["length", "c"], "defaults": [20, 4], "category": "Volatility"},
            "DONCHIAN": {"params": ["lower_length", "upper_length"], "defaults": [20, 20], "category": "Volatility"},
            "KC": {"params": ["length", "scalar"], "defaults": [20, 2], "category": "Volatility"},
            "MASSI": {"params": ["fast", "slow"], "defaults": [9, 25], "category": "Volatility"},
            "THERMO": {"params": ["length", "long", "short"], "defaults": [20, 2, -2], "category": "Volatility"},
            "VHF": {"params": ["length"], "defaults": [28], "category": "Volatility"},

            # Volume Indicators
            "OBV": {"params": [], "defaults": [], "category": "Volume"},
            "AD": {"params": [], "defaults": [], "category": "Volume"},
            "ADOSC": {"params": ["fast", "slow"], "defaults": [3, 10], "category": "Volume"},
            "AOBV": {"params": ["fast", "slow"], "defaults": [4, 12], "category": "Volume"},
            "CMF": {"params": ["length"], "defaults": [20], "category": "Volume"},
            "EFI": {"params": ["length"], "defaults": [13], "category": "Volume"},
            "EOM": {"params": ["length"], "defaults": [14], "category": "Volume"},
            "KVO": {"params": ["fast", "slow"], "defaults": [34, 55], "category": "Volume"},
            "MFI": {"params": ["length"], "defaults": [14], "category": "Volume"},
            "NVI": {"params": ["length"], "defaults": [255], "category": "Volume"},
            "PVI": {"params": ["length"], "defaults": [255], "category": "Volume"},
            "PVOL": {"params": [], "defaults": [], "category": "Volume"},
            "PVR": {"params": [], "defaults": [], "category": "Volume"},
            "PVT": {"params": [], "defaults": [], "category": "Volume"},
            "VWAP": {"params": [], "defaults": [], "category": "Volume"},

            # Trend Indicators
            "SUPERTREND": {"params": ["length", "multiplier"], "defaults": [10, 3], "category": "Trend"},
            "PSAR": {"params": ["af0", "af", "max_af"], "defaults": [0.02, 0.02, 0.2], "category": "Trend"},
            "ICHIMOKU": {"params": ["tenkan", "kijun", "senkou"], "defaults": [9, 26, 52], "category": "Trend"},
            "AMAT": {"params": ["fast", "slow"], "defaults": [8, 21], "category": "Trend"},
            "CHOP": {"params": ["length"], "defaults": [14], "category": "Trend"},
            "CKSP": {"params": ["p", "x", "q"], "defaults": [10, 1, 9], "category": "Trend"},
            "DECAY": {"params": ["kind"], "defaults": ["linear"], "category": "Trend"},
            "DECREASING": {"params": ["length", "strict"], "defaults": [1, False], "category": "Trend"},
            "DPO": {"params": ["length"], "defaults": [20], "category": "Trend"},
            "INCREASING": {"params": ["length", "strict"], "defaults": [1, False], "category": "Trend"},
            "LONG_RUN": {"params": ["fast", "slow"], "defaults": [2, 30], "category": "Trend"},
            "PSAR": {"params": ["af0", "af", "max_af"], "defaults": [0.02, 0.02, 0.2], "category": "Trend"},
            "QSTICK": {"params": ["length"], "defaults": [10], "category": "Trend"},
            "SHORT_RUN": {"params": ["fast", "slow"], "defaults": [2, 30], "category": "Trend"},
            "VORTEX": {"params": ["length"], "defaults": [14], "category": "Trend"},

            # Statistics
            "ENTROPY": {"params": ["length"], "defaults": [10], "category": "Statistical"},
            "KURTOSIS": {"params": ["length"], "defaults": [30], "category": "Statistical"},
            "MAD": {"params": ["length"], "defaults": [30], "category": "Statistical"},
            "MEDIAN": {"params": ["length"], "defaults": [30], "category": "Statistical"},
            "QUANTILE": {"params": ["length", "q"], "defaults": [30, 0.5], "category": "Statistical"},
            "SKEW": {"params": ["length"], "defaults": [30], "category": "Statistical"},
            "STDEV": {"params": ["length"], "defaults": [30], "category": "Statistical"},
            "VARIANCE": {"params": ["length"], "defaults": [30], "category": "Statistical"},
            "ZSCORE": {"params": ["length"], "defaults": [30], "category": "Statistical"},

            # Utility/Transform
            "ABERRATION": {"params": ["length", "atr_length"], "defaults": [5, 15], "category": "Utility"},
            "AO": {"params": ["fast", "slow"], "defaults": [5, 34], "category": "Utility"},
            "BIAS": {"params": ["length"], "defaults": [26], "category": "Utility"},
            "CDL_PATTERN": {"params": ["name"], "defaults": ["doji"], "category": "Pattern"},
            "CDL_Z": {"params": ["length"], "defaults": [30], "category": "Pattern"},
            "COPPOCK": {"params": ["length"], "defaults": [10], "category": "Utility"},
            "EBSW": {"params": ["length"], "defaults": [40], "category": "Utility"},
            "HA": {"params": [], "defaults": [], "category": "Utility"},
            "HILO": {"params": ["high_length", "low_length"], "defaults": [13, 21], "category": "Utility"},
            "HL2": {"params": [], "defaults": [], "category": "Price"},
            "HLC3": {"params": [], "defaults": [], "category": "Price"},
            "HWC": {"params": ["na", "nb", "nc"], "defaults": [0.2, 0.1, 0.1], "category": "Utility"},
            "LINREG": {"params": ["length"], "defaults": [14], "category": "Statistical"},
            "LOG_RETURN": {"params": ["length"], "defaults": [1], "category": "Utility"},
            "MIDPOINT": {"params": ["length"], "defaults": [2], "category": "Price"},
            "MIDPRICE": {"params": ["length"], "defaults": [2], "category": "Price"},
            "OHLC4": {"params": [], "defaults": [], "category": "Price"},
            "PDIST": {"params": [], "defaults": [], "category": "Utility"},
            "PERCENT_RETURN": {"params": ["length"], "defaults": [1], "category": "Utility"},
            "SLOPE": {"params": ["length"], "defaults": [1], "category": "Statistical"},
            "SSF": {"params": ["length", "poles"], "defaults": [10, 2], "category": "Utility"},
            "TOS_STDEVALL": {"params": ["length", "stds"], "defaults": [20, [1, 2, 3]], "category": "Statistical"},
            "TSIGNALS": {"params": ["trend", "asbool"], "defaults": [None, False], "category": "Utility"},
            "WCP": {"params": [], "defaults": [], "category": "Price"},
            "XSIGNALS": {"params": ["signal", "asbool"], "defaults": [None, False], "category": "Utility"}
        },
        "ta": {
            # Trend Indicators
            "SMAIndicator": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "EMAIndicator": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "WMAIndicator": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "KAMAIndicator": {"params": ["window", "pow1", "pow2"], "defaults": [10, 2, 30], "category": "Trend"},
            "PSARIndicator": {"params": ["step", "max_step"], "defaults": [0.02, 0.2], "category": "Trend"},
            "IchimokuIndicator": {"params": ["window1", "window2", "window3"], "defaults": [9, 26, 52], "category": "Trend"},
            "KeltnerChannel": {"params": ["window", "window_atr"], "defaults": [20, 10], "category": "Trend"},
            "DonchianChannel": {"params": ["window"], "defaults": [20], "category": "Trend"},
            "STCIndicator": {"params": ["window", "fast_period", "slow_period"], "defaults": [10, 23, 50], "category": "Trend"},

            # Momentum Indicators
            "RSIIndicator": {"params": ["window"], "defaults": [14], "category": "Momentum"},
            "MACD": {"params": ["window_slow", "window_fast", "window_sign"], "defaults": [26, 12, 9], "category": "Momentum"},
            "StochasticOscillator": {"params": ["window", "smooth_window"], "defaults": [14, 3], "category": "Momentum"},
            "StochRSIIndicator": {"params": ["window", "smooth1", "smooth2"], "defaults": [14, 3, 3], "category": "Momentum"},
            "WilliamsRIndicator": {"params": ["lbp"], "defaults": [14], "category": "Momentum"},
            "ADXIndicator": {"params": ["window"], "defaults": [14], "category": "Momentum"},
            "AroonIndicator": {"params": ["window"], "defaults": [14], "category": "Momentum"},
            "CCIIndicator": {"params": ["window"], "defaults": [14], "category": "Momentum"},
            "ROCIndicator": {"params": ["window"], "defaults": [12], "category": "Momentum"},
            "TSIIndicator": {"params": ["window_slow", "window_fast"], "defaults": [25, 13], "category": "Momentum"},
            "UltimateOscillator": {"params": ["window1", "window2", "window3"], "defaults": [7, 14, 28], "category": "Momentum"},
            "AwesomeOscillatorIndicator": {"params": ["window1", "window2"], "defaults": [5, 34], "category": "Momentum"},
            "KSTIndicator": {"params": ["roc1", "roc2", "roc3", "roc4", "window1", "window2", "window3", "window4"], "defaults": [10, 15, 20, 30, 10, 10, 10, 15], "category": "Momentum"},
            "PercentagePriceOscillator": {"params": ["window_slow", "window_fast", "window_sign"], "defaults": [26, 12, 9], "category": "Momentum"},
            "TRIXIndicator": {"params": ["window"], "defaults": [14], "category": "Momentum"},

            # Volatility Indicators
            "BollingerBands": {"params": ["window", "window_dev"], "defaults": [20, 2], "category": "Volatility"},
            "AverageTrueRange": {"params": ["window"], "defaults": [14], "category": "Volatility"},
            "UlcerIndex": {"params": ["window"], "defaults": [14], "category": "Volatility"},

            # Volume Indicators
            "OnBalanceVolumeIndicator": {"params": [], "defaults": [], "category": "Volume"},
            "AccDistIndexIndicator": {"params": [], "defaults": [], "category": "Volume"},
            "ChaikinMoneyFlowIndicator": {"params": ["window"], "defaults": [20], "category": "Volume"},
            "MFIIndicator": {"params": ["window"], "defaults": [14], "category": "Volume"},
            "VolumeWeightedAveragePrice": {"params": ["window"], "defaults": [14], "category": "Volume"},
            "VolumePriceTrendIndicator": {"params": [], "defaults": [], "category": "Volume"},
            "EaseOfMovementIndicator": {"params": ["window"], "defaults": [14], "category": "Volume"},
            "ForceIndexIndicator": {"params": ["window"], "defaults": [13], "category": "Volume"},
            "NegativeVolumeIndexIndicator": {"params": [], "defaults": [], "category": "Volume"},
            "PercentageVolumeOscillator": {"params": ["window_slow", "window_fast", "window_sign"], "defaults": [26, 12, 9], "category": "Volume"},
            "VortexIndicator": {"params": ["window"], "defaults": [14], "category": "Volume"},
            "MassIndex": {"params": ["window_fast", "window_slow"], "defaults": [9, 25], "category": "Volume"},

            # Others
            "CumulativeReturnIndicator": {"params": [], "defaults": [], "category": "Others"},
            "DailyReturnIndicator": {"params": [], "defaults": [], "category": "Others"},
            "DailyLogReturnIndicator": {"params": [], "defaults": [], "category": "Others"},
            "DPOIndicator": {"params": ["window"], "defaults": [20], "category": "Others"}
        },
        "technical": {
            # Moving Averages
            "SMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "EMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "WMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "HMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "HULL_MOVING_AVERAGE": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "DEMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "TEMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "ZEMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "ZLEMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "ZLHMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "ZLMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "VIDYA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "VWMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "TV_ALMA": {"params": ["period", "offset", "sigma"], "defaults": [20, 0.85, 6], "category": "Trend"},
            "TV_HMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "TV_TRAMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "TV_WMA": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "ROLLING_MEAN": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "ROLLING_WEIGHTED_MEAN": {"params": ["period"], "defaults": [20], "category": "Trend"},

            # Momentum Indicators
            "RSI": {"params": ["period"], "defaults": [14], "category": "Momentum"},
            "MACD": {"params": ["fast_period", "slow_period", "signal_period"], "defaults": [12, 26, 9], "category": "Momentum"},
            "STOCH": {"params": ["k_period", "d_period"], "defaults": [14, 3], "category": "Momentum"},
            "RMI": {"params": ["period"], "defaults": [14], "category": "Momentum"},
            "ROC": {"params": ["period"], "defaults": [10], "category": "Momentum"},
            "AWESOME_OSCILLATOR": {"params": ["fast_period", "slow_period"], "defaults": [5, 34], "category": "Momentum"},
            "WILLIAMS_PERCENT": {"params": ["period"], "defaults": [14], "category": "Momentum"},
            "STC": {"params": ["period", "fast_period", "slow_period"], "defaults": [10, 23, 50], "category": "Momentum"},
            "TDI": {"params": ["rsi_period", "fast_ma", "slow_ma"], "defaults": [13, 2, 7], "category": "Momentum"},
            "OSC": {"params": ["period"], "defaults": [14], "category": "Momentum"},

            # Volatility Indicators
            "ATR": {"params": ["period"], "defaults": [14], "category": "Volatility"},
            "ATR_PERCENT": {"params": ["period"], "defaults": [14], "category": "Volatility"},
            "BOLLINGER_BANDS": {"params": ["period", "std_dev"], "defaults": [20, 2], "category": "Volatility"},
            "WEIGHTED_BOLLINGER_BANDS": {"params": ["period", "std_dev"], "defaults": [20, 2], "category": "Volatility"},
            "TRUE_RANGE": {"params": [], "defaults": [], "category": "Volatility"},
            "ROLLING_STD": {"params": ["period"], "defaults": [20], "category": "Volatility"},
            "ROLLING_MAX": {"params": ["period"], "defaults": [20], "category": "Volatility"},
            "ROLLING_MIN": {"params": ["period"], "defaults": [20], "category": "Volatility"},
            "CHOPINESS": {"params": ["period"], "defaults": [14], "category": "Volatility"},
            "IMPLIED_VOLATILITY": {"params": ["period"], "defaults": [30], "category": "Volatility"},

            # Volume Indicators
            "PVT": {"params": [], "defaults": [], "category": "Volume"},
            "CHAIKIN_MONEY_FLOW": {"params": ["period"], "defaults": [20], "category": "Volume"},
            "CMF": {"params": ["period"], "defaults": [20], "category": "Volume"},
            "ROLLING_VWAP": {"params": ["period"], "defaults": [20], "category": "Volume"},
            "VFI": {"params": ["period"], "defaults": [130], "category": "Volume"},
            "VPCI": {"params": ["short_period", "long_period"], "defaults": [5, 25], "category": "Volume"},
            "VPCII": {"params": ["short_period", "long_period"], "defaults": [5, 25], "category": "Volume"},
            "VWMACD": {"params": ["fast_period", "slow_period", "signal_period"], "defaults": [12, 26, 9], "category": "Volume"},

            # Trend Indicators
            "SUPERTREND": {"params": ["period", "multiplier"], "defaults": [10, 3], "category": "Trend"},
            "ICHIMOKU": {"params": ["tenkan", "kijun", "senkou_b"], "defaults": [9, 26, 52], "category": "Trend"},

            "KELTNER_CHANNEL": {"params": ["period", "multiplier"], "defaults": [20, 2], "category": "Trend"},
            "SSLCHANNELS": {"params": ["period"], "defaults": [10], "category": "Trend"},
            "GENTRENDS": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "SEGTRENDS": {"params": ["period"], "defaults": [20], "category": "Trend"},
            "LAGUERRE": {"params": ["gamma"], "defaults": [0.7], "category": "Trend"},
            "EHLERS_SUPER_SMOOTHER": {"params": ["period"], "defaults": [10], "category": "Trend"},
            "TKE": {"params": ["period"], "defaults": [20], "category": "Trend"},

            # Pattern Recognition
            "DOJI": {"params": ["threshold"], "defaults": [0.1], "category": "Pattern"},
            "TD_SEQUENTIAL": {"params": [], "defaults": [], "category": "Pattern"},

            # Price Transform
            "MID_PRICE": {"params": ["period"], "defaults": [14], "category": "Price"},
            "TYPICAL_PRICE": {"params": [], "defaults": [], "category": "Price"},

            # Statistical
            "ZSCORE": {"params": ["period"], "defaults": [20], "category": "Statistical"},
            "FIBONACCI_RETRACEMENTS": {"params": [], "defaults": [], "category": "Statistical"},
            "FISHERS_INVERSE": {"params": ["period"], "defaults": [10], "category": "Statistical"},

            # Utility
            "RETURNS": {"params": ["period"], "defaults": [1], "category": "Utility"},
            "LOG_RETURNS": {"params": ["period"], "defaults": [1], "category": "Utility"},
            "BOUNCE": {"params": ["period"], "defaults": [5], "category": "Utility"},
            "TOUCHES": {"params": ["period"], "defaults": [5], "category": "Utility"},
            "WENT_UP": {"params": ["period"], "defaults": [1], "category": "Utility"},
            "WENT_DOWN": {"params": ["period"], "defaults": [1], "category": "Utility"},
            "IBS": {"params": [], "defaults": [], "category": "Utility"},
            "MADR": {"params": ["period"], "defaults": [20], "category": "Utility"}
        },
        "smc": {
            "BOS_CHOCH": {"params": ["swing_length"], "defaults": [10], "category": "Smart Money"},
            "FVG": {"params": ["threshold"], "defaults": [0.001], "category": "Smart Money"},
            "LIQUIDITY": {"params": ["swing_length"], "defaults": [5], "category": "Smart Money"},
            "OB": {"params": ["swing_length"], "defaults": [10], "category": "Smart Money"},
            "PREVIOUS_HIGH_LOW": {"params": ["length"], "defaults": [1], "category": "Smart Money"},
            "RETRACEMENTS": {"params": [], "defaults": [], "category": "Smart Money"},
            "SESSIONS": {"params": [], "defaults": [], "category": "Smart Money"},
            "SWING_HIGHS_LOWS": {"params": ["length"], "defaults": [10], "category": "Smart Money"}
        },
        "techcon": {
            "MACON": {"params": ["period"], "defaults": [20], "category": "Technical"},
            "OSCCON": {"params": ["period"], "defaults": [14], "category": "Technical"},
            "SUMCON": {"params": ["period"], "defaults": [10], "category": "Technical"}
        },

        "wqa101": {
            # WQA101 - 101 Quantitative Analysis Indicators (numbered 1-101)
            "1": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "2": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "3": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "4": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "5": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "6": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "7": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "8": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "9": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "10": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "11": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "12": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "13": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "14": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "15": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "16": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "17": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "18": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "19": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "20": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "21": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "22": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "23": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "24": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "25": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "26": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "27": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "28": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "29": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "30": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "31": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "32": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "33": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "34": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "35": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "36": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "37": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "38": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "39": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "40": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "41": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "42": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "43": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "44": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "45": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "46": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "47": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "48": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "49": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "50": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "51": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "52": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "53": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "54": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "55": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "56": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "57": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "58": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "59": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "60": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "61": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "62": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "63": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "64": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "65": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "66": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "67": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "68": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "69": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "70": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "71": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "72": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "73": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "74": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "75": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "76": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "77": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "78": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "79": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "80": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "81": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "82": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "83": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "84": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "85": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "86": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "87": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "88": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "89": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "90": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "91": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "92": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "93": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "94": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "95": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "96": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "97": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "98": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "99": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "100": {"params": ["period"], "defaults": [20], "category": "Quantitative"},
            "101": {"params": ["period"], "defaults": [20], "category": "Quantitative"}
        }
    }
